const anchors = [
  "放射",
  "被ばく",
  "被曝",
  "被爆",
  "除染",
  "線量",
  "ヨウ素",
  "セシウム",
  "シーベルト",
  "Sv",
  "mSV",
  "μSV",
  "uSV",
  "msv",
  "μsv",
  "usv",
  "ベクレル",
  "Bq",
  "ガンマ線",
  "γ線",
  "核種",
  "甲状腺",
  "甲状線",
  "チェルノブイリ",
  "規制値",
  "基準値",
  "学会",
  "警戒区域",
  "避難区域",
  "産科婦人科",
  "周産期・新生児医",
  "日本疫",
  "核医",
  "電力中央",
  "学術会議",
  "環境疫",
  "物理学会",
  "プルトニウム",
  "ストロンチウム",
  "暫定基準",
  "暫定規制",
  "屋内退避",
  "金町浄水場",
  "出荷制限",
  "管理区域",
  "避難地域",
  "モニタリング",
  "スクリーニング",
  "ホットスポット",
  "汚染",
  "検査 食品",
  "水",
  "土",
  "リスク がん",
  "ガン",
  "癌",
  "影響 妊婦",
  "妊娠",
  "出産",
  "子ども",
  "子供",
  "こども",
  "児",
  "母子避難",
  "避難弱者",
  "自主避難",
  "避難関連死",
  "避難死",
  "福島",
  "ふくしま",
  "フクシマ 避難",
  "米",
  "野菜",
  "牛肉",
  "食品",
  "産",
  "安全",
  "安心",
  "不安",
  "検査",
  "サーベイメータ",
  "半減期",
  "遮蔽",
  "疫学",
  "ICRP",
  "IAEA",
  "WHO",
  "コーデックス委員会",
  "ECRR",
  "JCO事故",
  "東海村事故",
  "東海村臨界",
  "臨界事故",
  "検査 野菜",
  "山野草",
  "魚",
  "東電",
  "東京電力",
  "安全委",
  "保安院",
  "規制庁",
  "規制委",
  "安全厨",
  "危険厨",
  "廃炉",
  "メルトダウン",
  "吉田調書",
  "再稼働",
  "反原発",
  "御用学者",
  "アイソトープ",
  "同位体",
  "同位元素",
  "いちえふ",
  "第五福竜",
  "ビキニ事件",
  "ビキニ事故",
  "死の灰",
  "風評",
];

const data = [
  {
    source:
      '<a href="http://genesix.co.jp/apps/ryugagotoku/" rel="nofollow">龍が如く for ツイッター</a>',
    id: 56624345312792577,
    user: {
      lang: "ja",
      protected: false,
      screen_name: "muratti0721",
      profile_background_tile: false,
      profile_text_color: "333333",
      profile_sidebar_fill_color: "F3F3F3",
      profile_sidebar_border_color: "DFDFDF",
      description:
        "あずみんのあずとさに悶死するピアス多いツーブロックでディップダイヘアなあず民odeN部次長。アイマス暦は5,6年だけど去年復帰Ｐ。通称逆立ちマンコキラメキラリJK。あず民Tの製作者。 春香P 好き/ﾃｸﾉ・ﾋﾟｱｽ・身体改造・アイドルマスター プロデュンヌです。 http://t.co/FOnlhOsj",
      profile_link_color: "990000",
      created_at: "2011-01-01 05:51:41",
      name: "むらっちP@あず民odeN部",
      id: 232756002,
      url: "http://com.nicovideo.jp/community/co520106",
      id_str: "232756002",
      location: "あずみんの家の家具と家具の隙間⇔東京",
      profile_background_color: "EBEBEB",
      time_zone: "Tokyo",
      profile_use_background_image: true,
    },
    id_str: "56624345312792577",
    retweeted_status: {
      id_str: "56616851194658816",
      id: 56616851194658816,
      user: { id_str: "24354829", id: 24354829 },
    },
    text:
      "RT @sakkan69: 「ちょっとうんこを漏らしたからって、それで私を軽蔑するなんて間違っています…！一生のうちたった一度、うっかりうんこが一尺漏れ出たからってそれが何なんです！世の中には、散々放射能を漏れ出させておいて、それを他人に後始末させて平気な顔してる人だって ...",
    entities: {
      user_mentions: [{ stop: 12, start: 3, screen_name: "sakkan69" }],
      hashtags: [],
      urls: [],
    },
    created_at: "2011-04-09 07:47:50",
  },
  {
    source: '<a href="http://twicca.r246.jp/" rel="nofollow">twicca</a>',
    id: 56624323204620288,
    user: {
      lang: "ja",
      protected: false,
      screen_name: "K_Overload",
      profile_background_tile: false,
      profile_text_color: "333333",
      profile_sidebar_fill_color: "DDEEF6",
      profile_sidebar_border_color: "C0DEED",
      description: "ﾝｱｲｷｬﾝﾄﾞｩｰｲｯ",
      profile_link_color: "0084B4",
      created_at: "2010-02-23 09:09:26",
      name: "TIC",
      id: 116692920,
      url: "http://twpf.jp/K_Overload",
      id_str: "116692920",
      location: "ぐにゃあ…",
      profile_background_color: "C0DEED",
      time_zone: "Hawaii",
      profile_use_background_image: true,
    },
    id_str: "56624323204620288",
    text:
      "よく考えたら拡散しちゃダメだww RT @sec5cm: 拡散RT @DIGIWK404: 拡散 RT @karashichan: 放射性物質拡散希望",
    entities: {
      user_mentions: [
        { stop: 27, start: 20, screen_name: "sec5cm" },
        { stop: 44, start: 34, screen_name: "DIGIWK404" },
        { stop: 64, start: 52, screen_name: "karashichan" },
      ],
      hashtags: [],
      urls: [],
    },
    created_at: "2011-04-09 07:47:45",
  },
  {
    source: "keitai_web",
    id: 56624311502516225,
    user: {
      lang: "ja",
      protected: false,
      screen_name: "ponsyon_jp",
      profile_background_tile: false,
      profile_text_color: "8C0000",
      profile_sidebar_fill_color: "E3E3E3",
      profile_sidebar_border_color: "B8B8B8",
      description: "つまらない者です。",
      profile_link_color: "144717",
      created_at: "2010-03-03 09:06:56",
      name: "ぱみゅぎこ",
      id: 119326035,
      id_str: "119326035",
      location: "",
      profile_background_color: "71CCD1",
      time_zone: "Sapporo",
      profile_use_background_image: true,
    },
    id_str: "56624311502516225",
    text:
      "屁理屈返しになるけど、「大多数が反原発を訴えてて、電力会社や推進派への(暴力的)圧力になりそうで怖い」と言ってる人は、3.11以前は「大多数が推進派で……」と憂えてたんだろうか？",
    entities: { user_mentions: [], hashtags: [], urls: [] },
    created_at: "2011-04-09 07:47:42",
  },
  {
    source:
      '<a href="http://twipple.jp/" rel="nofollow">ついっぷる   for iPhone</a>',
    id: 56624189188227072,
    user: {
      lang: "ja",
      protected: false,
      screen_name: "sasanoha1004",
      profile_background_tile: true,
      profile_text_color: "333333",
      profile_sidebar_fill_color: "CDE6A8",
      profile_sidebar_border_color: "EEEEEE",
      description:
        "基本、リツイート。\nだいぶ慣れたので、非公式RTやらハッシュタグやら使いながら好き勝手につぶやき。\nリア友の皆様にはご迷惑をおかけしております。",
      profile_link_color: "697531",
      created_at: "2010-05-20 17:55:16",
      name: "笹の葉",
      id: 146139634,
      id_str: "146139634",
      location: "概ね家か、電車の中",
      profile_background_color: "B2DFDA",
      time_zone: "Tokyo",
      profile_use_background_image: true,
    },
    id_str: "56624189188227072",
    retweeted_status: {
      id_str: "56622979903262720",
      id: 56622979903262720,
      user: { id_str: "13406122", id: 13406122 },
    },
    text:
      "RT @AmboTakashi: 福島県災害対策本部、東京電力広報室に電話確認したが、福島原発１号機爆発の報告は上がっていない。東電によると、ふくいちライブカメラが停止している件については、これから現地に確認する予定との事。#save_fukusima #sendai # ...",
    entities: {
      user_mentions: [{ stop: 15, start: 3, screen_name: "AmboTakashi" }],
      hashtags: [
        { stop: 126, text: "save_fukusima", start: 112 },
        { stop: 134, text: "sendai", start: 127 },
      ],
      urls: [],
    },
    created_at: "2011-04-09 07:47:13",
  },
  {
    source: '<a href="http://twicca.r246.jp/" rel="nofollow">twicca</a>',
    id: 56624168585797632,
    user: {
      lang: "ja",
      protected: false,
      screen_name: "ten_fnds",
      profile_background_tile: true,
      profile_text_color: "362720",
      profile_sidebar_fill_color: "E5507E",
      profile_sidebar_border_color: "CC3366",
      description:
        "職業：Tb奏者、ツアーバンド、スタジオミュージシャン、某バンドの中の人、ｅｔｃ　ニコニコ動画では主にボカロ系を中心に作詞活動してます。一応プロなので演奏系やったらズルイだろうとｗ　最近は世界の新着動画がお気に入りです。視聴者としてニコ動全体が好きです。",
      profile_link_color: "B40B43",
      created_at: "2009-02-13 13:25:36",
      name: "てん☆褌",
      id: 20769484,
      url: "http://www.nicovideo.jp/user/227004",
      id_str: "20769484",
      location: "世界の新着動画",
      profile_background_color: "FF6699",
      time_zone: "Tokyo",
      profile_use_background_image: true,
    },
    id_str: "56624168585797632",
    text:
      "そうか、動画じゃなく生の会見だからセカチャクじゃなくてクルーズだな、東電会見にクルーズ来いや！",
    entities: { user_mentions: [], hashtags: [], urls: [] },
    created_at: "2011-04-09 07:47:08",
  },
];
